server:
  address: localhost
  port: 8080
  servlet:
    context-path: /identity-service

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/ecommerce}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true